[server]
address = "127.0.0.1"
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#376983"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#233344"
font = "sans serif"
