[server]
address = "127.0.0.1"
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1D4938"
backgroundColor = "#F8F7F2"
secondaryBackgroundColor = "#EFF1E8"
textColor = "#203D32"
font = "sans serif"
